### ISSUE TITLE
Bug: Cannot open settings window

### ISSUE THREAD

**Issue by robbah** [2ndtlmining/Fluxnode#110]
The settings window doesn't open and i get errors in my console when clicking the settings button:

![image](https://github.com/2ndtlmining/Fluxnode/assets/3417515/14a7c4d7-12a8-4a1a-ba3f-63b25f6eded3)

**Comment by 2ndtlmining** [comment]
@robbah Thanks for send it through. I am having a look, cant seem to replacate.
I have deployed a small update yesterday could i please ask:

1. Noticed you using Brave? Have you tried Chrome, Firefox IE
2. Have you cleared cache and/or hard refresh (Shift + F5)
3. Getting same with mobile version?

Also check out with this wallet: t3c4EfxLoXXSRZCRnPRF3RpjPi9mBzF5yoJ

**Comment by robbah** [comment]
Hi @2ndtlmining,

1. I tried both Chrome and Firefox. Both doesn't work. Also Tor doesn't work.
2. Yes, doesn't work. Also in new private mode window.
3. Mobile also doesn't work. Both Brave as Firefox. i tried on Wifi and 4G

All tried with the wallet you provided.

**Comment by 2ndtlmining** [comment]
Super thanks. @robbah Ill keep looking, struggling to reproduce it

**Comment by robbah** [comment]
@2ndtlmining Did you try on a new device which hasn't been to the fluxnode dashboard?

**Comment by 2ndtlmining** [comment]
@robbah Thanks, yeah i have tested before on the wife and kids devices to test mobile specific features but most devices i have has been tested on before in some way shape or form. I did setup a new VM and can see what you relate to. Try figure out where its coming from

**Comment by robbah** [comment]
Maybe this helps.... i posted below some screenshots of the lines where the error come from:

![image](https://github.com/2ndtlmining/Fluxnode/assets/3417515/6c3c21d3-2b11-41f2-b3e7-fb2cd72b3d78)

![image](https://github.com/2ndtlmining/Fluxnode/assets/3417515/0eaa74c7-5750-4c6b-abdf-fa1c61920181)

![image](https://github.com/2ndtlmining/Fluxnode/assets/3417515/121fb38f-4bd6-4bc6-9a6d-576d662274a2)

**Comment by 2ndtlmining** [comment]
Thanks @robbah yeah there is a API value thats getting a null that i need to try track down

**Comment by robbah** [comment]
I want to change the currency to EUR. To which value should i change the selectedCurrency cookie?

**Comment by 2ndtlmining** [comment]
hey @robbah not sure, hope to have it fixed next week or so.

**Comment by 2ndtlmining** [comment]
@robbah just tested the fix thanks to some help from @buchi-1996 

<img width="1223" alt="image" src="https://github.com/2ndtlmining/Fluxnode/assets/108513481/37f7c2c6-c661-4088-ae35-a1aa560cf0e6">


Should  take a bit of time but hopefully in couple ours will propagate through the network

**Comment by robbah** [comment]
@2ndtlmining @buchi-1996 

Yes, it works! Thank you!
