### ISSUE TITLE
Request to add EUR

### ISSUE THREAD

**Issue by styleshifter** [2ndtlmining/Fluxnode#16]
Please add EUR for estimated earnings, flux value and wallet.

**Comment by 2ndtlmining** [comment]
@styleshifter Thanks for raising the request and feedback. I have had a look in the past to bring in more currencies making use of the free API's, however the reliability was not the best and cost for the good ones was a little high. But ill have another crack and see how it goes. Thanks

**Comment by victorquanlam** [comment]
I reckon we might be able to use rust-money package or Open Exchange Rates API which has free plan for up to 1000 calls a month.

**Comment by 2ndtlmining** [comment]
Awesome thanks. Looking at the amount refreshing people are doing think we will have to go down the DB route. Ill add it on the list for future releases hopefully some time in Q1. Rough idea

Pick 5 popular currencies
Retrieve Exchange rate once a day store in DB (Need to have a look at Flux hosting deal with DB synching)
Hit DB as many times as people refresh to reflect the daily exchange rate

**Comment by victorquanlam** [comment]
@2ndtlmining I will do a investigation spike to see if we can rust-money package to make unlimited conversions. Hopefully we don't have to go for the DB route.

**Comment by styleshifter** [comment]
Thanks guys! Keep up the good work. The page is already really good.
