### ISSUE TITLE
Tablet & Mobile responsiveness

### ISSUE THREAD

**Issue by 2ndtlmining** [2ndtlmining/Fluxnode#29]
### Problem statement

Focus thus far has been desktop usage, however looking at the analytics mobile and tablet usage is +-40%

### Proposed solution

- Improve responsiveness : Not sure how yet

**Comment by victorquanlam** [comment]
Seems like the issue is only with earning panel
![image](https://user-images.githubusercontent.com/53363594/215395452-25f7b556-8c5f-42ce-8bc9-08b6f55e2a06.png)

**Comment by victorquanlam** [comment]
proposed solution 
![image](https://user-images.githubusercontent.com/53363594/215400177-44d70da1-9f75-4bd5-bc5d-fe19f777cc59.png)

**Comment by 2ndtlmining** [comment]
Looks good so basically stretching it a bit longer

**Comment by victorquanlam** [comment]
> Looks good so basically stretching it a bit longer

That's right. We should utilise the screen resources when it comes to mobile and tablet screens.

**Comment by victorquanlam** [comment]
@2ndtlmining There's one more small thing. Let me know what you think
Current: 
![image](https://user-images.githubusercontent.com/53363594/215402300-e9856a62-6b62-4266-b09d-762d7234d11b.png)

New:
![image](https://user-images.githubusercontent.com/53363594/215402457-0ed79ef3-7f6d-4c3a-baea-dfeafe7674db.png)

**Comment by victorquanlam** [comment]
Technically, I expanded the width of wallet nodes in mobile screens so it won't feels much smaller compares to the other components.

**Comment by 2ndtlmining** [comment]
@victorquanlam It looks amazing thanks! Love it usiong the dead space on the sides. Really appreciate it.
