### ISSUE TITLE
Notable Nodes default

### ISSUE THREAD

**Issue by 2ndtlmining** [2ndtlmining/Fluxnode#33]
Some users missing the Notable node toggle not defaulting after search:

![image](https://user-images.githubusercontent.com/108513481/215355066-9dfc4456-d36f-47c6-b3e8-7050bcd2bf3b.png)

Could we have the Notable Nodes toggled on by default? Or remember where the user left it?

**Comment by victorquanlam** [comment]
Apply  appStore.setItem() function to solve this issue.
