### ISSUE TITLE
Donation Bug back :)

### ISSUE THREAD

**Issue by 2ndtlmining** [2ndtlmining/Fluxnode#41]
Hey Team

Looks like the Donation bug is back :)
Had a quick look on couple donations addesses:

(https://explorer.flux.zelcore.io/tx/9a4a4a74cdd2c608b90ad40b595566b18d78b9f13f3f4f9716524eeaa93eeb6b)

and

(https://explorer.flux.zelcore.io/tx/0614bbeb5cf8f48699332fe27b069b2d5689972eccc5a93f7f915c67268aac2a)

The donation item does not popup:

![image](https://user-images.githubusercontent.com/108513481/215861002-f44b887e-fcc4-4189-bcf7-6438000eb4d9.png)

Looking a the previous issue that change still there:

![image](https://user-images.githubusercontent.com/108513481/215861260-0a470ce2-3082-41b1-ae3a-ccb9d3f02174.png)

Not sure if the front end is just not calling for it

**Comment by victorquanlam** [comment]
For what it's worth, we should move the entire donation fetch out of global load too. It's slowing the initial loading state down a bit.

**Comment by 2ndtlmining** [comment]
@victorquanlam Thanks a lot. Apologies for the extra hassle

**Comment by victorquanlam** [comment]
@victorquanlam no worries, anytime 😄
