### ISSUE TITLE
Uptime Rework

### ISSUE THREAD

**Issue by 2ndtlmining** [2ndtlmining/Fluxnode#50]
### Problem Statement
Today we make use of the Uptime API to retrieve the data. For example:

![image](https://user-images.githubusercontent.com/108513481/216936471-508aa3d7-92e7-42e1-895a-38e8a15cc585.png)

![image](https://user-images.githubusercontent.com/108513481/216940096-38eacb71-691f-4997-94c6-33036fa714ea.png)

That retrieves the Flux OS uptime here:

![image](https://user-images.githubusercontent.com/108513481/216938684-d820c83e-0d8b-4fb5-8d28-6e7b3beb59aa.png)

Now this data displayed above is purely the Flux OS uptime. And what happens pretty frequently updates on Flux OS is pushed out and when Flux oS is updated this uptime gets reset. Eventhough the FLlux OS updates the uptime resets, which is not really a true reflection on the uptime of the node just by an Flux OS update. Like to update this to be a more true reflection of the actual node uptime and not the Flux OS uptime.

### Desired outcome

Like to make a couple changes:

- Calculation changes
- API Change
- Tooltips

**Calculation changes**

Like to fundamentally change the calcs to make use of the "Active since" field. Calculation needs to be (Time now) - (Active Since). Just need to make sure the data is converted correctly. Timestamp from API looks to be Unix. Thus need to apply the Js for it:

[Javascript timestamp](https://timestamp.online/article/how-to-convert-timestamp-to-datetime-in-javascript)

**API change**

Current pickup is:

`http://<IP>:<Port>/flux/uptime`

For example:

![image](https://user-images.githubusercontent.com/108513481/216944225-7ca35224-4dbd-4b44-8152-d85cebd6baaa.png)

Ideal:

`https://api.runonflux.io/daemon/viewdeterministiczelnodelist?filter=<Wallet>'`

example:

![image](https://user-images.githubusercontent.com/108513481/216945059-6d857274-382f-44c3-a655-b9c6e3e24639.png)

The above mentioned API is already used in the apidata.js file so should be able to use it and simplify the APIs at least.

**Tool-tip changes**

Current tool tip relates to Flux OS data we are extracting today:

![image](https://user-images.githubusercontent.com/108513481/217936930-dc9d0dea-0bb2-46d0-b0ff-580f2d3611d5.png)

As is: "Uptime is the amount of time Flux OS has been up. If Flux OS updates or restarts will reset the timer"
New: " Uptime is the amount of time since the Node has been started in Zelcore. If node is Offline or DOS in Zelcore the time will reset"

### Technical details

[Unix date](https://stackoverflow.com/questions/847185/convert-a-unix-timestamp-to-time-in-javascript)

**Comment by Hiroshi97** [comment]
@2ndtlmining Hi, by using new API endpoint, seems like it doesn't return all nodes with data. There is a few nodes that have no response data so their uptime can't be calculated. How should we display the uptime for that non-data nodes?

Node with data:
<img width="633" alt="image" src="https://user-images.githubusercontent.com/39031279/218308592-8e70bb51-cf4f-4724-a155-dc4a41890bdd.png">

Node without data:
<img width="631" alt="image" src="https://user-images.githubusercontent.com/39031279/218308613-802a8875-174b-4bae-b08e-561f33a097c0.png">

**Comment by 2ndtlmining** [comment]
Hey @Hiroshi97 

Not sure what the wallet address or IP is that you hitting that doesnt have any data but that i suspect will make sense just need to do some spot checks. I suspect no data will exist if the person hasnt started/confirmed their node on the network. Thus we should also not have received results in the past making use of the older api. That is my theory. If you have an example i can have a look, but using this we should only receive responses if the node is up and confirmed.

Hope that helps?

**Comment by Hiroshi97** [comment]
@2ndtlmining Thanks, the wallet address is: `t1K5txxB6GLmWezHeUANzVVGi8KjLmuvFyH`

Examples: 
https://api.runonflux.io/daemon/viewdeterministiczelnodelist?filter=31.7.195.26:16127
https://api.runonflux.io/daemon/viewdeterministiczelnodelist?filter=195.206.229.60:16127
https://api.runonflux.io/daemon/viewdeterministiczelnodelist?filter=195.206.229.59:16127
https://api.runonflux.io/daemon/viewdeterministiczelnodelist?filter=195.206.229.51:16127

**Comment by 2ndtlmining** [comment]
@Hiroshi97 Ok this sort of make sense for me i think. 

Long story. Per IP you can have up to 8 nodes by enabling UPnP. So what i tried to have a look at is our current solution vs what we are thinking:

https://fluxnode.app.runonflux.io/#/nodes?wallet=t1K5txxB6GLmWezHeUANzVVGi8KjLmuvFyH

![image](https://user-images.githubusercontent.com/108513481/218387056-54bcf195-f57d-4eff-94d0-fca0d078ce3e.png)

There is 8 IP's or nodes on that one IP: 31.7.195.26

31.7.195.26 (Default, which normally would be on 16126)
31.7.195.26: 161<XX>. For example:

31.7.195.26
31.7.195.26:16137
31.7.195.26:16147
31.7.195.26:16157
31.7.195.26:16167
31.7.195.26:16177
31.7.195.26:16187
31.7.195.26:16197

Would always be in that range 16137->16197, plus the default.


<br class="Apple-interchange-newline">
</body>
</html>

Looking at the deterministic call:

![image](https://user-images.githubusercontent.com/108513481/218387580-59a40879-8c59-40c2-9a0f-e0483e1ce3d3.png)

The value is in that list, but without that port number. As that looks to be the default port. If i remember back we are adding + 1 which i think will not work in this case. 

Not sure if we can use the default IP without the UPnP port? Or even if this makes sense :)

**Comment by 2ndtlmining** [comment]
Not going ahead with this for now
