### ISSUE TITLE
Fractus minimum storage size is too high

### ISSUE THREAD

**Issue by w2vy** [2ndtlmining/Fluxnode#89]
It was 9250 but was later reduced to 9000

**Comment by 2ndtlmining** [comment]
Thanks for letting me know mate. I can fix that on the website

**Comment by 2ndtlmining** [comment]
@w2vy When you have a bit of time could you please test the UAT site, made the update:

https://fluxnodeuat.app.runonflux.io/

Unfortunately i dont own any fractus nodes so hard for me to test :)

**Comment by w2vy** [comment]
Looks good to me!

**Comment by 2ndtlmining** [comment]
@w2vy Thanks for raising the issue and testing really appreciate the feedback. Pushed to prod.
